"""Schema complet initial

Revision ID: ee1c9a8686b1
Revises: 
Create Date: 2026-05-08 01:59:20.951018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1c9a8686b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backfill_status',
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'exchange', 'source')
    )
    op.create_table('central_bank_rates',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('country_iso3', sa.String(length=3), nullable=False),
    sa.Column('rate_type', sa.String(length=30), nullable=False),
    sa.Column('rate_value', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('decision_type', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', 'country_iso3', 'rate_type')
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('country_iso3', sa.String(length=3), nullable=True),
    sa.Column('is_fiat', sa.Boolean(), nullable=False),
    sa.Column('xof_fixed', sa.Boolean(), nullable=False),
    sa.Column('xof_rate', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('data_collection_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('route_name', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('api_cost_units', sa.Integer(), nullable=True),
    sa.Column('raw_data_path', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_ratios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('period_ending', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('market_cap_usd', sa.BigInteger(), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('forward_pe', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('peg_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_to_book', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ev_to_ebitda', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('ev_to_revenue', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('current_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('gross_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('operating_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('net_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ebitda_margin', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('return_on_assets', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('return_on_equity', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('beta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('payout_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('earnings_growth', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('revenue_growth', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period_ending')
    )
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('period_ending', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=True),
    sa.Column('statement_type', sa.String(length=20), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_revenue', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebit', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('ebitda', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('basic_eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('diluted_eps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_assets', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('net_debt', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('working_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('investing_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('financing_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('capital_expenditure', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'period_ending', 'period_type', 'statement_type')
    )
    op.create_table('fx_rates',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('quote_currency', sa.String(length=10), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('obs_status', sa.String(length=5), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', 'base_currency', 'quote_currency', 'rate_type')
    )
    op.create_table('market_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('country_iso3', sa.String(length=3), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_symbols', sa.String(length=500), nullable=True),
    sa.Column('impact_forex', sa.Boolean(), nullable=False),
    sa.Column('impact_equity', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('auto_detected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_sentiment',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vix', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('vix_change', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('em_spread_bps', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('oil_prices',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('brent_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('wti_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('nat_gas_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gold_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('price_daily',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=True),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('close_usd', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('split_ratio', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('dividend', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', 'symbol')
    )
    op.create_table('wb_documents',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('countries', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wb_publication_log',
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('country_iso3', sa.String(length=3), nullable=False),
    sa.Column('data_year', sa.Integer(), nullable=False),
    sa.Column('first_seen_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('indicator_code', 'country_iso3', 'data_year')
    )
    op.create_table('wb_revisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_iso3', sa.String(length=3), nullable=True),
    sa.Column('indicator_code', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('old_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('new_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('revision_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pct_change', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('income_level', sa.String(length=50), nullable=True),
    sa.Column('capital_city', sa.String(length=100), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('wb_region_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso3')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('country_iso3', sa.String(length=3), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('eodhd_code', sa.String(length=20), nullable=True),
    sa.Column('fcs_exchange', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_iso3'], ['countries.iso3'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('macro_indicators',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('country_iso3', sa.String(length=3), nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('indicator_name', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('value_normalized', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('yoy_change', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mom_change', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_multiplier', sa.String(length=20), nullable=True),
    sa.Column('frequency', sa.String(length=10), nullable=True),
    sa.Column('obs_status', sa.String(length=5), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_iso3'], ['countries.iso3'], ),
    sa.PrimaryKeyConstraint('date', 'country_iso3', 'indicator_code')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange_code', sa.String(length=20), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('instrument_type', sa.String(length=20), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('country_iso3', sa.String(length=3), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_trade_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_iso3'], ['countries.iso3'], ),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['exchange_code'], ['exchanges.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'exchange_code')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ceo', sa.String(length=200), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('hq_country', sa.String(length=3), nullable=True),
    sa.Column('hq_city', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('market_cap_usd', sa.BigInteger(), nullable=True),
    sa.Column('shares_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('shares_float', sa.BigInteger(), nullable=True),
    sa.Column('beta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('data_quality', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hq_country'], ['countries.iso3'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    op.drop_table('instruments')
    op.drop_table('macro_indicators')
    op.drop_table('exchanges')
    op.drop_table('countries')
    op.drop_table('wb_revisions')
    op.drop_table('wb_publication_log')
    op.drop_table('wb_documents')
    op.drop_table('price_daily')
    op.drop_table('oil_prices')
    op.drop_table('market_sentiment')
    op.drop_table('market_events')
    op.drop_table('fx_rates')
    op.drop_table('financial_statements')
    op.drop_table('financial_ratios')
    op.drop_table('data_collection_log')
    op.drop_table('currencies')
    op.drop_table('corporate_actions')
    op.drop_table('central_bank_rates')
    op.drop_table('backfill_status')
    # ### end Alembic commands ###
